### ISSUE TITLE
Source code and license missing

### ISSUE THREAD

**Issue by IzzySoft** [mirfatif/WhatsRunning#1]
Err… on purpose, of just forgotten to push? :wink:

**Comment by mirfatif** [comment]
On purpose. But if you want I can give you access to the private repo 🙂

**Comment by IzzySoft** [comment]
Aw, I was afraid of that. I was just about adding it to my repo to accompany your other app – but without it being open-source it's not an option unfortunately as you know :wink: Thanks nevertheless for making it available here, even the pro variant! Should you one day decide to open-source it, please let me know and I gladly pick up again.

**Comment by ghost** [comment]
The core reason why some Devs close the source, is to force people into buying their application. It's against the very nature of development & privacy.
There's always been this same debate between open & closed source communities. Can't do anything ¯\\\_(ツ)_/¯

**Comment by maks** [comment]
This app asks for:
>WhatsRunning requires root or at least ADB privileges.

yet with no source available, no offence @mirfatif, why would anyone place any trust in your app, especially the amount of trust required to run at such an elevated privilege level?

**Comment by mirfatif** [comment]
[Why WhatsRunning requires root or ADB access?](https://mirfatif.github.io/WhatsRunning/help/help#faq1)

Ideally what WhatsRunning and many other root apps do should be the built-in functionality of Android. But Android doesn't want us to have access to low level information and control over our devices because it affects Google's business model. So root or ADB is unavoidable to take control back. Or live with what your OEM offers.

Why isn't my app open-source?
- I wrote 40000+ lines of code. So I've the right to decide if I make it open-source or not.
- Someone advised me: make a project open-source only if you plan to abandon it in near future. And I agree with this.
 I'm the author of 3 open-source apps written completely from scratch by myself. And my experience with open-source community hasn't been very pleasant, unfortunately. The community is always so demanding, and very thankless, even rude at times. You try to help people with their privacy and ignorance, they point out your faults. You offer 75% functionality for free, they seem to be concerned only about the remaining 25%.
 Dealing with corporate devils like Google on one side, and open-source community on the other side is a nightmare, even if you do it as a full-time job. And it's not only me. I'm not a developer but a learner. But even senior developers get fed up of this. [Here](https://forum.xda-developers.com/t/app-5-0-fairemail-fully-featured-open-source-privacy-oriented-email-app.3824168/page-1087#post-86909365) is a recent example.
- I tried to split the functionality of my app into free (which will be open sourced) and pro versions but failed to come up with a reasonable idea. Still looking for something workable.

Why would you place trust in my app?

- You should not. But if you are using an Android device, even with postmarketOS or GrapheneOS or even Replicant, it's extremely unlikely that your device is 100% open-source. Cellular modem firmware, binary blobs (HALs) i.e. userspace drivers of many hardware components, stock ROMs shipped by almost all OEMs, even the kernel source sometimes, the whole Google Mobile Suite shipped by many OEMs with their stock ROMs, everything is closed-source.
 So if you place that much trust in corporate giants, why so much sensitivity against an innocent individual who is trying to protect his own and others' privacy?
- There's a long list of root apps (including Magisk modules, Xposed modules etc.) which aren't open source but they are useful and we use them.
- Even if your device isn't rooted, but you install an app from millions of closed-source apps available on Play Store, and you give it access to your device identifiers / contacts / log / messages / location / mic / camera / gallery / storage etc. you are putting an equal amount of trust you put by granting root access to an app. Google Play Services have access to almost all of the above. So is the case with system apps bundled by OEMs.
- Free version of my app (which is completely ad-free and tracker free, though crippled in functionality) can be used completely offline. Pro version installed from Play Store doesn't need direct internet access for license verification. So it can also be used completely offline. It nullifies - or at least largely reduces - the risk of privacy breach.
- I've answered this question very clearly:
  > [How much privacy friendly WhatsRunning is?](https://mirfatif.github.io/WhatsRunning/help/help#faq4)
  >
  > We are not interested in you or your device at all. We do not spy on you. We do not collect your data in any way, not even the crash logs. We believe in our users being educated, well-informed, and in-charge of their privacy. WhatsRunning strengthens you to protect your privacy.

  Similar questions from my other app PMX:
  - [Is PMX spying on me using ADB over network?](https://mirfatif.github.io/PermissionManagerX/help/help#faq27)
  - [Is PMX misusing root privileges to collect my data?](https://mirfatif.github.io/PermissionManagerX/help/help#faq28)

  Same applies to WhatsRunning.
- And the [Privacy Policy](https://mirfatif.github.io/WhatsRunning/PRIVACY.html) clearly states:
  > I DO NOT collect and retain any personally identifiable information about you or your device, like user name, address, location, pictures etc.
- Scan my app with any on-device or online malware scanner or privacy auditor like [Exodus Privacy](https://reports.exodus-privacy.eu.org/en/reports/273846/) or Addon Detector and you won't find any privacy concerns.
- You are welcome to reverse-engineer my app, or watch its network and on-device activity in whatever way you want (many have already done this). And if you find anything shady, please question me and I'll give explanation.

**Comment by IzzySoft** [comment]
> why so much sensitivity against an innocent individual

In general, always be suspicious – especially with big corps mostly being out for profit, but also to single individuals suddenly producing the "super app". But in the case here: Irfan already has earned his trust. So while in general I'd rather go with FOSS, I understand his reasoning and would trust his app.

**Comment by mirfatif** [comment]
> So while in general I'd rather go with FOSS...

Same here. FOSS is satisfaction. Even if the code has never been audited, and never been reviewed, which is usually the case.

**Comment by maks** [comment]
@mirfatif you are very much entitled to release your app in any way you wish, I'm certainly not trying to pressure you to release it under an open source licence. I merely pointed out that given its need for high privileges and lack of source code *and* your argument for people to not naively trust OEM vendors seem at odds.

I'm sad to hear that you've had poor experience with the open source community, as a long term open source maintainer, I've had my share of poor experiences also, but also positive ones too, given it's made up of humans, that would be my expectation for any community, but I personally continue to work towards making the community a better and more inclusive and welcoming.

In regards to some of your comments, while its fashionable to label large corporations with nasty names, its good to remember that they are not individuals, they are made up of individuals, essentially again human communities and should be treated as such. Therefore its worth looking at facts instead of making emotive accusations. Eg. Android is an operating system, so logically it cannot: "...doesn't want us to have access to low level information and control over our devices" in fact it cannot want or need anything. Android is however, at Google's own choosing distributed under an open source license. The AOSP project continues to exist and be funded by Google the corporation. As you yourself pointed out, many projects make use of AOSP for all sorts of purposes, none of which need Googles approval as long as they themselves abide by the relevant software licenses involved.

Finally to address some of your points on trust.

It's not a zero sum game nor of course black and white. Providing a strawman of saying someone would completely trust a OEM or corp software vendor and yet not you makes no sense, I hope you can see that.

>There's a long list of root apps (including Magisk modules, Xposed modules etc.) which aren't open source but they are useful and we use them.

You may choose to trust and use those modules, but I and many others do not.

Overall I commend you for making this app! I'm sure many will use it and find it useful.
Personally, I'll choose not to use it and will keep looking for a open source alternative.

**Comment by mirfatif** [comment]
> Personally, I'll choose not to use it and will keep looking for a open source alternative.

I appreciate your response and really respect your choice.
